- name: "checking if set: apache2_vhost_rewrite_rule_target"
  when: apache2_vhost_rewrite_engine_enabled and apache2_vhost_rewrite_rule_target == "https://as.in.certificate.example.com/$1 [R]"
  fail: 
    msg: "Please set apache2_vhost_rewrite_rule_target to a syntax like: {{ apache2_vhost_rewrite_rule_target }}"

- name: "checking if set: apache2_vhost_ssl_certificate_file when apache2_vhost_ssl_enabled"
  when: apache2_vhost_ssl_certificate_file == '' and apache2_vhost_ssl_enabled
  fail:
    msg: Please set apache2_vhost_ssl_certificate_file

- name: "checking if set: apache2_vhost_ssl_certificate_key_file when apache2_vhost_ssl_enabled"
  when: apache2_vhost_ssl_certificate_key_file == '' and apache2_vhost_ssl_enabled
  fail:
    msg: Please set apache2_vhost_ssl_certificate_key_file

- name: "checking if set: apache2_vhost_hotfolder_fs_path when apache2_vhost_hotfolder_enabled"
  when: apache2_vhost_hotfolder_fs_path == '' and apache2_vhost_hotfolder_enabled
  fail:
    msg: Please set apache2_vhost_hotfolder_fs_path

- name: "make sure that config directories are created: sites-enabled/easydb5/include-before (and after)"
  file:
    state: directory
    path: "{{ file_item.path }}"
    #owner: "{{ file_item.owner | default('www-data') }}"
    #group: "{{ file_item.group | default('www-data') }}"
    #mode: "{{ file_item.mode | default(0755) }}"
  loop_control:
    loop_var: file_item
  with_items:
    - path: /etc/apache2/sites-enabled/easydb5/include-before
    - path: /etc/apache2/sites-enabled/easydb5/include-after

# Either:
- name: deploying http vhost
  template: 
    src: etc/apache2/sites-enabled/http.conf.j2
    dest: /etc/apache2/sites-enabled/easydb.conf
  when: not apache2_vhost_ssl_enabled
  notify:
    - restart apache2 
# Or:
- name: deploying https vhost
  template: 
    src: etc/apache2/sites-enabled/https.conf.j2
    dest: /etc/apache2/sites-enabled/easydb.conf
  when: apache2_vhost_ssl_enabled
  notify:
    - restart apache2 

# always checking ...

- name: checking whether apache2 config is valid
  command: apache2ctl configtest

- meta: flush_handlers

- name: checking that apache2 is running
  systemd:
    name: apache2
    state: started
