- name: "checking if set: apache2_vhost_rewrite_rule_target"
  when: apache2_vhost_rewrite_engine_enabled and apache2_vhost_rewrite_rule_target == "https://as.in.certificate.example.com/$1 [R]"
  fail: 
    msg: "Please set apache2_vhost_rewrite_rule_target to a syntax like: {{ apache2_vhost_rewrite_rule_target }}"

- name: "checking if set: apache2_vhost_ssl_certificate_file"
  when: apache2_vhost_ssl_certificate_file == '' and apache2_vhost_ssl_enabled
  fail:
    msg: Please set apache2_vhost_ssl_certificate_file

- name: "checking if set: apache2_vhost_ssl_certificate_key_file"
  when: apache2_vhost_ssl_certificate_key_file == '' and apache2_vhost_ssl_enabled
  fail:
    msg: Please set apache2_vhost_ssl_certificate_key_file

# Either:
- name: deploying http vhost
  template: 
    src: etc/apache2/sites-enabled/http.conf.j2
    dest: /etc/apache2/sites-enabled/easydb.conf
  when: not apache2_vhost_ssl_enabled
  notify:
    - restart apache2 
# Or:
- name: deploying https vhost
  template: 
    src: etc/apache2/sites-enabled/https.conf.j2
    dest: /etc/apache2/sites-enabled/easydb.conf
  when: apache2_vhost_ssl_enabled
  notify:
    - restart apache2 

# always checking ...

- name: checking whether apache2 config is valid
  command: apache2ctl configtest

- meta: flush_handlers

- name: checking that apache2 is running
  systemd:
    name: apache2
    state: started
